feat(titres): ajoute un bouton "centrer sur la zone" sur la carte principale
MTES-MCT/camino-ui pull request #158
Opened 2020-08-11 14:10 UTC by NeoBahamut

2020-08-11 14:12 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(ui): ajoute un bouton "centrer sur la zone" sur la carte principale](https://trello.com/c/9BXO6yUR/565-featui-ajoute-un-bouton-centrer-sur-la-zone-sur-la-carte-principale)

2020-08-24 08:36 UTC, vmaubert requested changes

2020-08-24 08:36 UTC, vmaubert commented on src/components/titres/filtres-url.vue
> +    // Enregistre le zoom et le centre initaux dans les preferences avec les valeurs courantes
Je ne comprends pas ce qu’on fait dans cette méthode. On va lire 2 valeurs dans le store et on dispatch dans le store les 2 valeurs qu’on vient de lire. Donc on fait rien ?

2020-08-25 06:52 UTC, vmaubert requested changes

2020-08-25 06:52 UTC, vmaubert commented on src/components/titres/filtres-url.vue
> +      this.preferencesMapIni()
Méthode d’une seule ligne, on peut donc remplacer la méthode directement par son contenu

2020-08-25 06:52 UTC, vmaubert commented on src/store/titres.js
> +    const zoomIni = this.state.titres.preferences.carte.zoom
Le state est accessible en tant que paramètre de la méthode (cf méthodes au dessus), ça permettra d’enlever le `this`.

2020-08-25 07:18 UTC, vmaubert requested changes

2020-08-25 07:18 UTC, vmaubert commented on src/components/titres/map.vue
> +      this.$store.dispatch('titres/preferencesSet', {
Même remarque, je pense que ceci est plus adapté directement dans le store avec une action `titres/preferencesMapReset`.

2020-08-25 07:37 UTC, vmaubert approved these changes

2020-08-25 08:08 UTC, francoisromain reviewed
je ne crois pas que ce soit ce qui qui est attendu par la carte trello. 

Ce qui est attendu par la carte trello: un bouton qui cadre tous les markers qui pourraient s'afficher sur la carte avec les filtres selectionnés.

2020-09-16 07:09 UTC, francoisromain commented
remplacé par https://github.com/MTES-MCT/camino-ui/pull/169

2020-09-16 07:09 UTC, closed without merging