feat(geo): gère les virgules et les espaces quand l'utilisateur saisit des coordonnées décimales
MTES-MCT/camino-ui pull request #166
Opened 2020-09-04 07:18 UTC by NeoBahamut

2020-09-04 07:18 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(geo): gère les virgules et les espaces quand l'utilisateur saisit des coordonnées décimales](https://trello.com/c/0Qg6kGXL/592-featgeo-g%C3%A8re-les-virgules-et-les-espaces-quand-lutilisateur-saisit-des-coordonn%C3%A9es-d%C3%A9cimales)

2020-09-10 13:58 UTC, vmaubert requested changes

2020-09-10 13:58 UTC, vmaubert commented on src/components/_ui/input-number.vue
> +    :class="{ 'mb-s': value, mb: !value }"
On peut enlever les props `min` et `placeholder` => https://fr.vuejs.org/v2/guide/components-props.html#Attributs-non-props

2020-09-10 13:58 UTC, vmaubert commented on src/components/_ui/input-number.vue
> +    placeholder: { type: String, default: '' }
cf commentaire précédent

2020-09-10 13:58 UTC, vmaubert commented on src/components/titre/etape/edit-fondamentales.vue
> +        />
La checkbox `donnée incertaine` a disparu

2020-09-10 13:58 UTC, vmaubert commented on src/components/titre/etape/edit-fondamentales.vue
> +    control(el, field, type) {
Cette méthode est utilisée ?

2020-09-10 14:51 UTC, NeoBahamut commented on src/components/titre/etape/edit-fondamentales.vue
> +    control(el, field, type) {
non, j'ai oublié de la retirer... bien vu, merci

2020-09-10 15:11 UTC, vmaubert approved these changes

2020-09-10 15:11 UTC, merged