feat(carte): ajoute un bouton pour cadrer tous les marqueurs
MTES-MCT/camino-ui pull request #169
Opened 2020-09-10 15:00 UTC by francoisromain

2020-09-10 15:58 UTC, vmaubert requested changes

2020-09-10 15:58 UTC, vmaubert commented on src/components/map/index.vue
> +    fitBoundsPrevent(bounds) {
Cette méthode n’est pas utilisée

2020-09-10 16:03 UTC, vmaubert commented
Si je me déplace sur la carte, que je vais sur la vue liste et que je reviens sur carte, je reviens exactement au même endroit. Mais ce scénario ne fonctionne pas après avoir cliqué sur « Tout afficher ».

2020-09-10 16:07 UTC, francoisromain commented
exact l'url n'est pas mise à jour correctement lorsqu'on clique sur "tout afficher". je regarde

2020-09-11 18:24 UTC, francoisromain commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(map): recadre la carte selon les résultats de recherche](https://trello.com/c/BWOxQqce/324-featmap-recadre-la-carte-selon-les-r%C3%A9sultats-de-recherche)

2020-09-11 18:24 UTC, francoisromain commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(map): recadre la carte selon les résultats de recherche](https://trello.com/c/BWOxQqce/324-featmap-recadre-la-carte-selon-les-r%C3%A9sultats-de-recherche)

2020-09-14 07:44 UTC, vmaubert approved these changes

2020-09-14 07:45 UTC, merged