[WIP] fix(nombres): formater l'affichage des nombre au standard français
MTES-MCT/camino-ui pull request #179
Opened 2020-09-21 15:27 UTC by NeoBahamut

2020-09-21 15:27 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [fix(nombre) : formater l'affichage des nombre au standard français (virgule pour les décimales)](https://trello.com/c/wp3huLKF/1001-fixnombre-formater-laffichage-des-nombre-au-standard-fran%C3%A7ais-virgule-pour-les-d%C3%A9cimales)

2020-09-22 15:54 UTC, francoisromain requested changes
c'est pas mal, mais ça n'est pas l'objet de la carte trello… 

Il s'agit de "formater l'affichage". Il faut donc chercher tous les composants qui affichent des nombres (dans les étapes, les activités, les travaux, les coordonnées géo etc.) et les formater avec `numberFormat`

2020-09-28 07:19 UTC, francoisromain requested changes
voir mon commentaire précédent : https://github.com/MTES-MCT/camino-ui/pull/179#pullrequestreview-493613395

2020-09-29 07:13 UTC, francoisromain requested changes
il manque le formatage de l'affichage des props

2020-09-29 07:13 UTC, francoisromain commented on src/components/_common/edit-section-element.vue
> +            <inputNumber
c'est de la saisie, pas de l'affichage. ça va dans l'autre PR

2020-09-29 07:13 UTC, francoisromain commented on src/components/titre/travau-etape/edit.vue
> +            <inputNumber
idem

2020-10-01 11:11 UTC, francoisromain approved these changes

2020-10-01 11:11 UTC, merged