fix(travaux): corrige l'erreur lors de la saisie de la surface
MTES-MCT/camino-ui pull request #190
Opened 2020-09-25 14:05 UTC by NeoBahamut

dans la console : '_vm.etape.incertitudes is undefined'

2020-09-25 14:06 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [fix(travaux): corrige l'erreur dans la console '_vm.etape.incertitudes is undefined' lors de la saisie de la surface](https://trello.com/c/xuvcS7O4/1057-fixtravaux-corrige-lerreur-dans-la-console-vmetapeincertitudes-is-undefined-lors-de-la-saisie-de-la-surface)

2020-09-28 07:10 UTC, francoisromain commented on src/components/titre/travau-etape/edit.vue
> +        <label v-if="etape.surface && etape.incertitudes" class="h5">
je ne comprend pas la logique: la checkbox incertitude ne va s'afficher que si `etape.incertitudes` est true. comment fiat l'utilisateur pour valier cette checkbox si elle n'est pas affcihée ?

2020-09-28 07:39 UTC, francoisromain requested changes

2020-09-28 07:39 UTC, francoisromain commented on src/components/titre/travau-etape/edit.vue
> +        <label v-if="etape.surface && etape.incertitudes" class="h5">
à ce stade, il n'y a pas d'incertitudes sur les travaux. On peut supprimer le bloc

2020-09-28 08:10 UTC, francoisromain commented
corrigé ici : https://github.com/MTES-MCT/camino-ui/commit/5c2e5d42619e0b8085aad188bcaa01d722d620be

2020-09-28 08:10 UTC, closed without merging