feat: édite une administration
MTES-MCT/camino-ui pull request #208
Opened 2020-10-26 17:15 UTC by francoisromain

2020-10-26 17:18 UTC, francoisromain commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat: ajout de la gestion des permissions sur les pages administrations](https://trello.com/c/eEd8TKNs/1075-feat-ajout-de-la-gestion-des-permissions-sur-les-pages-administrations)

2020-10-26 17:19 UTC, francoisromain commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat: édite une administration](https://trello.com/c/2Krqwlmp/1107-feat-%C3%A9dite-une-administration)

2020-10-27 08:58 UTC, vmaubert requested changes
Dans la fiche d’une administration

- L’adresse n’est pas complète, il manque les champs adresse
- Il manque le type
- Il manque le service
- lI manque l’accent sur departement
- Il manque la majuscule et l’accent sur region

2020-10-27 09:06 UTC, francoisromain commented
> Dans la fiche d’une administration
> 
>     * L’adresse n’est pas complète, il manque les champs adresse
> 
>     * Il manque le type
> 
>     * Il manque le service
> 
>     * lI manque l’accent sur departement
> 
>     * Il manque la majuscule et l’accent sur region

corrigé

2020-10-27 09:09 UTC, merged