feat(etapes): pouvoir définir le type d’une propriété number
MTES-MCT/camino-ui pull request #212
Opened 2020-11-04 17:36 UTC by NeoBahamut

2020-11-04 17:37 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(etapes): pouvoir définir le type d’une propriété number](https://trello.com/c/ckJUChWf/1017-featetapes-pouvoir-d%C3%A9finir-le-type-dune-propri%C3%A9t%C3%A9-number)

2020-11-13 08:47 UTC, vmaubert approved these changes

2020-11-13 09:26 UTC, francoisromain requested changes
Il y a encore des problèmes: 
- si on tape une valeur qui n'est pas un nombre (p.e.: `---1.5` ou `1,5.5` et que l'on valide, le point est supprimé sans aucune information)

2020-11-16 11:15 UTC, francoisromain requested changes
ajouter des tests

2020-11-16 17:40 UTC, francoisromain approved these changes
good job !

2020-11-16 17:41 UTC, francoisromain commented
il reste une erreur de lint

2020-11-17 07:40 UTC, vmaubert approved these changes

2020-11-17 09:17 UTC, merged