fix(statistiques): corrige les stats granulats marins : chiffres et forme
MTES-MCT/camino-ui pull request #235
Opened 2021-01-13 14:41 UTC by NeoBahamut

2021-01-13 14:42 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat (statistique): ajoute onglet Granulats Marins](https://trello.com/c/dEei055r/1154-feat-statistique-ajoute-onglet-granulats-marins)

2021-01-14 14:37 UTC, vmaubert requested changes

2021-01-14 14:37 UTC, vmaubert commented on src/components/statistiques/granulats-marins.vue
> +                Demandes en cours d'instruction (initiales et modification en
`modification` ne devrait pas être au pluriel aussi ?

2021-01-14 14:37 UTC, vmaubert commented on src/components/statistiques/granulats-marins.vue
> +        Évolution du nombre de titres et de leur surface octroyés chaque année
Si c’est les titres qui sont octroyés, je changerai en `Évolution du nombre de titres octroyés`, si c’est les surfaces alors il y a un pb `leur surface octroyée` (ou `leurs surfaces octroyées` ?)

2021-01-14 16:16 UTC, NeoBahamut commented on src/components/statistiques/granulats-marins.vue
> +                Demandes en cours d'instruction (initiales et modification en
je viens de relire, en fait tout est au singulier... je change....

2021-01-14 16:21 UTC, NeoBahamut commented on src/components/statistiques/granulats-marins.vue
> +        Évolution du nombre de titres et de leur surface octroyés chaque année
C'est Guillaume qui l'a écrit ainsi, et je comprends ceci : "évolution du nombre de titres octroyés, et de leur surface, chaque année"... non ?

2021-01-15 09:00 UTC, vmaubert commented on src/components/statistiques/granulats-marins.vue
> +        Évolution du nombre de titres et de leur surface octroyés chaque année
Oui je le comprends aussi ainsi, mais j’ai du relire la phrase. Alors que si on l’écrit directement comme tu viens de le dire `évolution du nombre de titres octroyés, et de leur surface, chaque année` alors il n’y a plus d’ambiguïté.

2021-01-18 12:33 UTC, francoisromain requested changes

2021-01-18 12:33 UTC, francoisromain commented on src/components/statistiques/granulats-marins-activite.vue
> +            m3
`m3` -> `m³`

2021-01-18 12:33 UTC, francoisromain commented on src/components/statistiques/granulats-marins.vue
> +              <RouterLink
le mieux serait d'ajouter explicitement le lien sous le titre avec une mention `Voir les titres`

2021-01-18 12:33 UTC, francoisromain commented on src/components/statistiques/granulats-marins.vue
> +              <RouterLink
idem

2021-01-18 12:33 UTC, francoisromain commented on src/components/statistiques/granulats-marins.vue
> +              <RouterLink
idem

2021-01-18 12:33 UTC, francoisromain commented on src/components/statistiques/granulats-marins.vue
> +      <BarChart
problème de mise en page: un div.blobs doit toujours contenir des div.blob. Supprimer le parent si ça n'est pas le cas

2021-01-18 12:33 UTC, francoisromain commented on src/styles/camino.css
> +.routerLinkStats {
supprimer ce style

2021-01-18 13:49 UTC, NeoBahamut commented on src/components/statistiques/granulats-marins.vue
> +        Évolution du nombre de titres et de leur surface octroyés chaque année
convaincu

2021-01-18 13:50 UTC, NeoBahamut commented on src/components/statistiques/granulats-marins-activite.vue
> +            m3
je le remet, mais ça décale l'alignement.

2021-01-18 13:51 UTC, NeoBahamut commented on src/components/statistiques/granulats-marins-activite.vue
> +            m3
je vais voir si j'arrive à corriger ce décalage

2021-01-18 16:39 UTC, francoisromain approved these changes

2021-01-18 16:40 UTC, merged