feat(activites): ajoute des descriptions pour les types d'activité
MTES-MCT/camino-ui pull request #300
Opened 2021-04-14 09:28 UTC by NeoBahamut

affiche les descriptions dans les rapports, et dans l'administration des types d'activité

2021-04-14 09:28 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(activités) pour chaque type de rapport, faire référence à l'article du code minier adéquat.](https://trello.com/c/KDWEIiyl/1429-featactivit%C3%A9s-pour-chaque-type-de-rapport-faire-r%C3%A9f%C3%A9rence-%C3%A0-larticle-du-code-minier-ad%C3%A9quat)

2021-04-14 13:37 UTC, francoisromain requested changes
On devrait aussi afficher cette description sur l'activité en lecture

2021-04-14 13:37 UTC, francoisromain commented on src/components/activite/edit-popup.vue
> +        <h2 class="cap-first mb-1">
`mb-1`, c'est quoi ?

2021-04-14 13:41 UTC, NeoBahamut commented on src/components/activite/edit-popup.vue
> +        <h2 class="cap-first mb-1">
c'était pour mettre un margin-bottom pour espacer avec l'année
je réalise qu'il n'existe pas dans les css, pourtant ça rendait bien...
Je vais mettre un mb-m ou mb-l

2021-04-20 08:19 UTC, francoisromain approved these changes

2021-04-20 08:19 UTC, merged