fix: formate la date dans une section
MTES-MCT/camino-ui pull request #317
Opened 2021-05-03 15:23 UTC by francoisromain

2021-05-03 15:23 UTC, francoisromain commented
![](https://github.trello.services/images/mini-trello-icon.png) [fix(date): on utilise des formats de dates différents](https://trello.com/c/rbwjSLVe/1512-fixdate-on-utilise-des-formats-de-dates-diff%C3%A9rents)

2021-05-03 15:56 UTC, vmaubert requested changes

2021-05-03 15:56 UTC, vmaubert commented on src/components/_common/section-element.vue
> +        {{ dateFormat(valeur) }}
C’est pas plus élégant de le faire dans le computed `valeur()` ?

2021-05-04 13:48 UTC, vmaubert approved these changes

2021-05-04 13:48 UTC, merged