fix(stats): corrige l'échelle et rajoute la légende des concessions v…
MTES-MCT/camino-ui pull request #319
Opened 2021-05-04 14:52 UTC by NeoBahamut

…alides des granulats marins

2021-05-04 14:55 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [fix(affichage): échelle et légendes page statistiques](https://trello.com/c/CLotcxfp/1520-fixaffichage-%C3%A9chelle-et-l%C3%A9gendes-page-statistiques)

2021-05-04 15:06 UTC, francoisromain commented on src/components/statistiques/granulats-marins.vue
> +      <div class="tablet-float-blobs clearfix">
qu'est ce qui corrige l'échelle ?

2021-05-05 12:47 UTC, NeoBahamut commented on src/components/statistiques/granulats-marins.vue
> +      <div class="tablet-float-blobs clearfix">
l'échelle du graph est correcte. 
moi, j'ai compris que c'était la taille du graph qu'il fallait corriger puisqu'il est sur la totalité de la largeur et non pas sur les 2/3

2021-05-10 07:58 UTC, francoisromain requested changes

2021-05-10 07:58 UTC, francoisromain commented on src/components/statistiques/_utils.js
> +  return titreType &&
complètement illisible… Qu'est ce que ça fait ?

à minima il faut le décomposer et rajouter des if / else

2021-05-10 12:50 UTC, francoisromain approved these changes

2021-05-10 12:50 UTC, merged