fix(permission) : corrige l'erreur de tracking de permission utilisateur
MTES-MCT/camino-ui pull request #366
Opened 2021-06-29 11:54 UTC by NeoBahamut

2021-06-29 11:59 UTC, vmaubert requested changes

2021-06-29 11:59 UTC, vmaubert commented on src/stats/index.js
> -      app.config.globalProperties.$matomo = matomo
T’as un pb en local avec cette ligne ?

2021-06-29 11:59 UTC, vmaubert commented on src/stats/custom-variables.js
> +    if (user.permission) {
Je vais essayer de regarder le pb

2021-06-29 11:59 UTC, vmaubert commented on src/stats/custom-variables.js
> +  // console.log('user :>> ', user)
Volontaire ça ?

2021-06-29 12:07 UTC, NeoBahamut commented on src/stats/index.js
> -      app.config.globalProperties.$matomo = matomo
oui
je n'arrive pas à la synchroniser avec la master

2021-06-29 12:09 UTC, NeoBahamut commented on src/stats/custom-variables.js
> +  // console.log('user :>> ', user)
oups
non désolé...

2021-06-30 04:58 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [fix(permissions) : corrige l'erreur de tracking de permission utilisateur](https://trello.com/c/nE5CAutv/1597-fixpermissions-corrige-lerreur-de-tracking-de-permission-utilisateur)

2021-06-30 08:45 UTC, vmaubert approved these changes
j’ai pas trouvé

2021-06-30 08:45 UTC, merged