feat(metas): affiche l'id et le nom des metas dans les relations
MTES-MCT/camino-ui pull request #367
Opened 2021-06-30 07:38 UTC by NeoBahamut

2021-07-06 06:54 UTC, NeoBahamut commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat: améliore l'ux de l'édition des métas](https://trello.com/c/74NxjG2Y/1161-feat-am%C3%A9liore-lux-de-l%C3%A9dition-des-m%C3%A9tas)

2021-07-06 14:42 UTC, vmaubert requested changes

2021-07-06 14:42 UTC, vmaubert commented on src/components/meta.vue
> +                    v-if="definition.update && colonne.type === Number"
Pourquoi c’est pas un `v-else-if` avec `EditObject` ?

2021-07-07 06:56 UTC, NeoBahamut commented on src/components/meta.vue
> +                    v-if="definition.update && colonne.type === Number"
j'ai voulu séparer le `EditObject` du reste, mais ça sert à rien, c'est vrai
c'est bon, j'ai corrigé

2021-07-15 09:49 UTC, vmaubert commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(metas): affiche le label à coté de chaque ids](https://trello.com/c/HpCpSB9T/1608-featmetas-affiche-le-label-%C3%A0-cot%C3%A9-de-chaque-ids)

2021-07-15 11:20 UTC, merged