feat(uploads): présente une anim de chargement pendant les téléversements de fichiers
MTES-MCT/camino-ui pull request #385
Opened 2021-09-15 12:50 UTC by dheavy

2021-09-21 06:23 UTC, vmaubert commented on src/store/document.js
> +        fichierNouveau.id = `${document.date}-${document.typeId}-${uuidv4()}`
Ca je ne comprends pas pourquoi on fait ça

2021-09-21 06:23 UTC, vmaubert commented on src/api/_client.js
> +const apiUploadFetch = document => apiFetch(uploadCall, 'uploads', document)
Si ça marche c'est cool, mais je ne comprends pas comment ça peut marcher :-/

2021-09-21 06:29 UTC, vmaubert commented on src/api/_client.js
> +    chunkSize: MEGA_BYTE * 2,
Pourquoi ne pas mettre CHUNK_SIZE en constante ?

2021-09-21 06:29 UTC, vmaubert commented on src/store/index.js
> +      Object.assign(state, { loading: [] })
Je ne vois pas le cas d'usage

2021-09-22 09:52 UTC, dheavy commented
@vmaubert au début j'ai consolidé les champs input dans un composant dédié parce que j'avais pour lui d'autres plans (je pensais y mettre le feedback de chargement, ne connaissant pas encore la structure existante). Mais ces plans sont devenus rapidement obsolète, donc le bien-fondé de ce changement là devient discutable. Le seul réel gain par rapport au code suivant, c'est finalement de n'avoir écrit le label "Choisir un fichier..." qu'à un seul endroit.

A voir si ça te dérange.

2021-09-22 12:03 UTC, dheavy commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(upload): mettre un loader pendant l’upload d’un fichier.](https://trello.com/c/zURCD2ed/1668-featupload-mettre-un-loader-pendant-lupload-dun-fichier)

2021-09-22 13:22 UTC, vmaubert requested changes

2021-09-22 13:22 UTC, vmaubert commented on src/api/_client.js
> +const uploadCall = async (file, documentId, progressCb) => {
Faire un fichier dédié à l’upload ça sera plus simple à maintenir

2021-09-22 13:22 UTC, vmaubert commented on src/store/document.js
> +      setTimeout(() => {
Pourquoi on met ça dans un timeout ? 

2021-09-23 14:20 UTC, vmaubert commented on src/components/etape-edition.vue
> -        :on-save="save"
C’était quoi ça ? 

2021-09-23 14:31 UTC, dheavy commented on src/components/etape-edition.vue
> -        :on-save="save"
Plutôt que de recevoir une callback (`save`) en prop (`on-save`) qui sera invoquée par l'enfant (`FormSaveBtn`), l'enfant émet vers son parent l'événement natif qui est émis en son sein (voir `$emit('click', $event)` dans `FormSaveBtn`). La première méthode est très React, la second totalement idiomatique pour Vue. Petit oubli.

2021-09-29 07:49 UTC, vmaubert commented
@dheavy je n’arrive pas à modifier un pdf d’un document existant.
Je mets un premier pdf sur un doc d’une étape, j’enregistre l’étape.
Je retourne en édition, je modifie le document ci-dessous avec un nouveau pdf, j’enregistre.
Si je télécharge le pdf, je récupère le 1er et non le 2ème.

2021-09-30 14:30 UTC, vmaubert approved these changes

2021-09-30 14:30 UTC, merged