feat(page/admin): complète les informations sur l'envoi des emails
MTES-MCT/camino-ui pull request #432
Opened 2021-11-24 09:40 UTC by dheavy

https://trello.com/c/yMkhbVyh/54-feat-page-administration-ajouter-texte-explicatif-sur-emails-%C3%A0-notifier-lors-du-d%C3%A9p%C3%B4t-dun-type-dactivit%C3%A9

<img width="1322" alt="Capture d’écran 2021-11-24 à 10 39 12" src="https://user-images.githubusercontent.com/543614/143213371-a26f2077-5501-4337-a617-1beff2081d6f.png">

2021-11-24 09:40 UTC, dheavy commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat (page administration) : ajouter texte explicatif sur "Emails à notifier lors du dépôt d’un type d’activité"](https://trello.com/c/yMkhbVyh/54-feat-page-administration-ajouter-texte-explicatif-sur-emails-%C3%A0-notifier-lors-du-d%C3%A9p%C3%B4t-dun-type-dactivit%C3%A9)

2021-11-24 10:11 UTC, vmaubert requested changes

2021-11-24 10:11 UTC, vmaubert commented on src/components/administration/activites-types-emails.vue
> +          <li>Les <strong>DREAL, DEAL et DGTM</strong> sont notifiées pour tous les dépôts d'activité.</li>
Je pense plutôt que le texte est dynamique en fonction du type de l’administration en cours de consultation.

2021-11-24 10:47 UTC, vmaubert requested changes

2021-11-24 10:47 UTC, vmaubert commented on src/components/administration/activites-types-emails.vue
> +      return ['dea', 'dre'].includes(this.administration?.type?.id)
Il ne manque pas les ministères ? 

2021-11-24 10:47 UTC, vmaubert commented on src/components/administration/activites-types-emails.vue
> +            Les <strong>DREAL, DEAL et DGTM</strong> sont notifiées pour tous
Tu trouves pas ça bizarre ? On est sur une administration, donc on connait son type. 
Est-ce qu’il faudrait pas mettre un truc « Lors d’un dépôt d’une activité avec une production non nulle (ou pas) d’un type en particulier, quels sont les emails à notifier ? »

2021-11-24 15:11 UTC, dheavy commented on src/components/administration/activites-types-emails.vue
> +      return ['dea', 'dre'].includes(this.administration?.type?.id)
Ils ne sont pas mentionnés dans la carte ("les Dreal, deal et DGTM sont notifiées pour tous les dépôts d'activité, alors que les autres administrations (préfecture, DIRM, préfet maritime...) sont notifiées uniquement si la production annuelle est non nulle").

Je les rajoute ?

2021-11-25 08:44 UTC, vmaubert commented on src/components/administration/activites-types-emails.vue
> +      return ['dea', 'dre'].includes(this.administration?.type?.id)
C’est pas ce que tu as codé côté API ? 

2021-11-25 08:46 UTC, vmaubert commented on src/components/administration/activites-types-emails.vue
> +            (si la production annuelle est non nulle)</span
Ne faudrait-il pas mettre cette précision en valeur pour ne pas la rater. Donc enlever les parenthèses et mettre en gras, qu’en penses-tu ? 

2021-11-25 09:32 UTC, dheavy commented on src/components/administration/activites-types-emails.vue
> +      return ['dea', 'dre'].includes(this.administration?.type?.id)
si effectivement !

2021-11-25 13:47 UTC, vmaubert approved these changes

2021-11-25 13:47 UTC, merged