feat(proprietes): masque l'affichage des dates début/fin pour admin
MTES-MCT/camino-ui pull request #434
Opened 2021-11-24 14:36 UTC by dheavy

2021-11-25 08:43 UTC, vmaubert requested changes
J’ai l’impression que la demande n’était pas claire, car c’est pas du tout ce qu’on souhaite.
Sans parler des erreurs dans le code (ligne 55 et 56 qui s’enchainent avec la même condition).
J’ai mis à jour la carte Trello avec les tests à effectuer pour la recette. Je suis dispo pour en parler.

2021-11-25 15:15 UTC, vmaubert commented on src/components/etape/fondamentales-edit.vue
> +        ['arm', 'axm'].includes(this.titreTypeId)
il y a déjà des `computed` => `isArm()` et `isAxm()`

2021-11-29 11:53 UTC, dheavy commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat(propriétés) : masquer les champs "date de début" et "date d'échéance" pour les profils "admin"](https://trello.com/c/ytG8LdNU/93-featpropri%C3%A9t%C3%A9s-masquer-les-champs-date-de-d%C3%A9but-et-date-d%C3%A9ch%C3%A9ance-pour-les-profils-admin)

2021-11-29 12:23 UTC, vmaubert requested changes
Tu fais une deuxième PR pour les amodiataires ? 

2021-11-29 12:23 UTC, vmaubert commented on src/components/etape/fondamentales-edit.vue
> -      <hr />
C’est voulu ? 

2021-11-29 12:23 UTC, vmaubert commented on jest.config.js
> +    '@/(.*)$': '<rootDir>/src/$1'
Je ne comprends pas la modification, tu as trouvé un problème ? 

2021-11-29 14:07 UTC, dheavy commented on jest.config.js
> +    '@/(.*)$': '<rootDir>/src/$1'
Oui : les composants qui importaient des fichiers à l'aide de l'alias `@` (pour `src`) marchait très bien en dev, mais ces imports échouaient en tests. Et s'en était la raison.

2021-11-29 14:16 UTC, dheavy commented
@vmaubert j'allais faire une deuxième PR pour amodiataires mais c'est se compliquer pour rien finalement. Je ferais tout dans celle-ci

2021-11-29 14:46 UTC, vmaubert requested changes

2021-11-29 14:46 UTC, vmaubert commented on src/components/etape/fondamentales-edit.vue
> +      <hr v-if="canSeeAllDates" />
On peut pas le mettre dans le `div` juste au dessus ? 

2021-11-30 10:23 UTC, merged