feat(document): implémente l'aperçu des PDFs
MTES-MCT/camino-ui pull request #439
Opened 2021-12-06 15:18 UTC by dheavy

2021-12-06 15:41 UTC, dheavy commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat (affichage) : possibilité d'avoir un aperçu des documents ou justificatifs (pdf)](https://trello.com/c/WjqK0r5P/53-feat-affichage-possibilit%C3%A9-davoir-un-aper%C3%A7u-des-documents-ou-justificatifs-pdf)

2021-12-07 09:20 UTC, vmaubert requested changes

2021-12-07 09:20 UTC, vmaubert commented on src/components/document/preview-popup.vue
> +      <div v-else class="p-s full-x bold">Enregistrement en cours…</div>
Message obsolète ? 

2021-12-07 09:20 UTC, vmaubert commented on src/components/document/preview-popup.vue
> +interface IDocument {
On a vraiment besoin de tous les attributs pour faire une preview pdf  ?

2021-12-07 09:20 UTC, vmaubert commented on src/components/documents/tr.vue
> +        v-if="document.fichier || document.fichierNouveau"
faut pas aussi vérifier `boutonVisualisation` ?

2021-12-07 09:20 UTC, vmaubert commented on src/styles/system/margins.css
> +.ml-auto {
Existe déjà sous le nom de `flex-right`

2021-12-07 09:20 UTC, vmaubert commented on src/styles/system/ui.css
> +.pdf-visualizer-container {
Que penses-tu de mettre ça directement dans le composant ? 

2021-12-07 09:29 UTC, vmaubert commented on src/components/documents/tr.vue
> +        class="btn-border ml-auto py-s px-m my--xs"
il manque la classe `rnd-l-xs`

2021-12-07 11:54 UTC, dheavy commented
@vmaubert c'est mieux de ne pas squash, comme ça on a un commit avec le code utilisant PDF.js pour une éventuelle future référence.

2021-12-07 12:15 UTC, vmaubert requested changes

2021-12-07 12:15 UTC, vmaubert commented on src/components/documents/tr.vue
> +          (boutonVisualisation && document.fichier) || document.fichierNouveau
certain de cette condition ? 

2021-12-07 14:47 UTC, vmaubert reviewed
Ça ouvre une page blanche sur le document de l’ouverture de l’enquête au public de w-cx-astrolabe-2009

2021-12-14 12:44 UTC, vmaubert commented
@dheavy tu peux rebase stp ? 

2021-12-14 12:53 UTC, dheavy commented
> @dheavy tu peux rebase stp ?

All good

2021-12-14 15:10 UTC, merged