feat(demande): commence l'implémentation du téléchargement du zip
MTES-MCT/camino-ui pull request #442
Opened 2021-12-08 15:15 UTC by dheavy

Nécessite le merge de cette PR (https://github.com/MTES-MCT/camino-ui/pull/439) au préalable pour éviter un rebase compliqué.

https://trello.com/c/wMpfBA7s/52-feat-t%C3%A9l%C3%A9chargement-possibilit%C3%A9-de-t%C3%A9l%C3%A9charger-toutes-les-pi%C3%A8ces-dun-dossier-de-demande-en-zip

2021-12-08 15:16 UTC, dheavy commented
https://trello.com/c/wMpfBA7s/52-feat-t%C3%A9l%C3%A9chargement-possibilit%C3%A9-de-t%C3%A9l%C3%A9charger-toutes-les-pi%C3%A8ces-dun-dossier-de-demande-en-zip

2021-12-09 09:01 UTC, vmaubert requested changes

2021-12-09 09:01 UTC, vmaubert commented on src/components/etape/preview.vue
> +    async downloadZipDemande() {
De mon point de vue, c’est du taff pour l’API.
Bundle plus petit, même comportement sur tous les navigateurs et OS…

2021-12-09 09:16 UTC, dheavy commented on src/components/etape/preview.vue
> +    async downloadZipDemande() {
Ok

2021-12-09 14:39 UTC, dheavy commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat (téléchargement) : possibilité de télécharger toutes les pièces d'un dossier de demande en .zip](https://trello.com/c/wMpfBA7s/52-feat-t%C3%A9l%C3%A9chargement-possibilit%C3%A9-de-t%C3%A9l%C3%A9charger-toutes-les-pi%C3%A8ces-dun-dossier-de-demande-en-zip)

2021-12-09 16:22 UTC, vmaubert requested changes

2021-12-09 16:22 UTC, vmaubert commented on src/store/titre-etape.js
> +      const sliceSize = 512 // ~ meilleures performances pour le découpage
Tout ce traitement est obsolète si on le fait en REST, non ? 

2021-12-13 11:19 UTC, dheavy commented on src/store/titre-etape.js
> +      const sliceSize = 512 // ~ meilleures performances pour le découpage
Non, sauf si l'on change le traitement actuel (génération d'un flux de données à traiter par le receveur — ici le frontend compacte l'ensemble pour en faire un zip téléchargeable) pour un traitement du type création de fichier physique sur le serveur + retourner un lien.

2021-12-14 12:36 UTC, vmaubert requested changes

2021-12-14 12:36 UTC, vmaubert commented on src/components/etape/preview.vue
> +      <div v-if="etape.type.id === 'mfr'" class="flex">
Et si il n’y a pas documents ? 

2021-12-14 12:36 UTC, vmaubert commented on src/components/etape/preview.vue
> +    async downloadDemande() {
dans tout le code on essaye de mettre le verbe à la fin du nom de la méthode

2021-12-14 12:36 UTC, vmaubert commented on src/store/titre-etape.js
> +      commit('isDownloading', true)
On ne peut pas utiliser le `fileLoading` de la ligne juste au dessus ? 

2021-12-15 07:41 UTC, vmaubert requested changes

2021-12-15 07:41 UTC, vmaubert commented on src/components/etape/preview.vue
> +        this.etape.justificatifs?.length
Si il y a des docs OU des justificatifs, non ? 

2021-12-15 13:25 UTC, vmaubert requested changes

2021-12-15 13:25 UTC, vmaubert commented on src/components/etape/preview.vue
> +        (this.etape.documents?.length && this.etape.justificatifs?.length)
💥

2021-12-15 13:27 UTC, vmaubert commented on src/components/etape/preview.vue
> +      isDownloading: state => Boolean(state.loading.length)
On ne sait pas trop ce qu’il y a dans « loading », je pense qu’il est plus prudent de vérifier juste la présence du chargement souhaité.

2021-12-15 13:44 UTC, merged