fix(travaux): corrige la visibilité de l’onglet travaux pour les administrations locales
MTES-MCT/camino-ui pull request #444
Opened 2021-12-14 14:20 UTC by vmaubert

2021-12-14 14:21 UTC, vmaubert commented
![](https://github.trello.services/images/mini-trello-icon.png) [feat (travaux) : les agents en administration centrale (DGALN, DGPR) n'ont pas la visibilité sur l'onglet travaux, alors qu'ils devraient l'avoir](https://trello.com/c/GLGMvjgF/78-feat-travaux-les-agents-en-administration-centrale-dgaln-dgpr-nont-pas-la-visibilit%C3%A9-sur-longlet-travaux-alors-quils-devraient-l)

2021-12-14 15:10 UTC, dheavy commented
@vmaubert reste juste à corriger les tests

2021-12-14 16:34 UTC, dheavy commented on src/store/titre.js
> +    return state.element?.demarches?.filter(d => !d.type.travaux)
Je viens de me rendre compte que dans le code (que j'avais écris...) on risque ici une autre erreur potentielle : si state.element ou state.element.demarches sont null ou undefined, sauf erreur de ma part, le getter passe ces valeurs à `src/components/titre.vue` ligne 72, qui le soumet aux props de son composant TitreDemarches, levant une exception pour cause de props non conforme (il attend un array).

2021-12-14 16:36 UTC, dheavy requested changes
Que penses-tu de s'assurer que ces getters renvoient des arrays vides, si falsy ?

2021-12-15 07:55 UTC, vmaubert commented
> Que penses-tu de s'assurer que ces getters renvoient des arrays vides, si falsy ?

Bien vu !

2021-12-15 08:00 UTC, dheavy approved these changes

2021-12-15 08:00 UTC, merged